package com.maple.dao.mapper;

import com.maple.model.CreditBill;
import com.maple.model.CreditBillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CreditBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_bill
     *
     * @mbggenerated
     */
    int countByExample(CreditBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_bill
     *
     * @mbggenerated
     */
    int deleteByExample(CreditBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_bill
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_bill
     *
     * @mbggenerated
     */
    int insert(CreditBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_bill
     *
     * @mbggenerated
     */
    int insertSelective(CreditBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_bill
     *
     * @mbggenerated
     */
    List<CreditBill> selectByExampleWithRowbounds(CreditBillExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_bill
     *
     * @mbggenerated
     */
    List<CreditBill> selectByExample(CreditBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_bill
     *
     * @mbggenerated
     */
    CreditBill selectByPrimaryKey(String accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_bill
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CreditBill record, @Param("example") CreditBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_bill
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CreditBill record, @Param("example") CreditBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_bill
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CreditBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_bill
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CreditBill record);
}